import{a as p,i as c,S as F}from"./assets/vendor-D1eTGYtO.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const i of document.querySelectorAll('link[rel="modulepreload"]'))l(i);new MutationObserver(i=>{for(const s of i)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function a(i){const s={};return i.integrity&&(s.integrity=i.integrity),i.referrerPolicy&&(s.referrerPolicy=i.referrerPolicy),i.crossOrigin==="use-credentials"?s.credentials="include":i.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(i){if(i.ep)return;i.ep=!0;const s=a(i);fetch(i.href,s)}})();p.defaults.baseURL="https://pixabay.com";function u({q:t="query",page:e=1,per_page:a=15}={q:"query",page:1,per_page:15}){return p.get("/api/",{params:{key:"45131353-6378824e083214db07911a1d4",q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:e,per_page:a}}).then(({data:l})=>l)}const L=document.querySelector(".img-container-list"),b=document.querySelector(".loader");function f(t){if(b.style.display="none",!t.length){c.show({title:"Error",titleColor:"#FAFAFB",titleSize:"16px",titleLineHeight:"24px",position:"topRight",maxWidth:"432px",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#FAFAFB",messageSize:"16px",messageLineHeight:" 24px",backgroundColor:"#EF4040"});return}L.insertAdjacentHTML("beforeend",w(t)),new F(".wrap-img-item a",{captions:!0,captionsData:"alt",captionDelay:250}).refresh()}function w(t){return t.map(({webformatURL:e,largeImageURL:a,tags:l,likes:i,views:s,comments:d,downloads:x})=>`<li class="img-container-item">
        <div class="wrap-img-item">
            <a href="${a}"><img class="img-item" src="${e}" alt="${l}"/></a>
        </div>
        <div class="wrap-img-discr">
            <ul class="img-discr-list">
                <li class="img-discr-item">
                    <h2 class="img-discr-item-header">Likes</h2>
                    <p class="img-discr-item-text">${i}</p>
                </li>
                <li class="img-discr-item">
                    <h2 class="img-discr-item-header">Views</h2>
                    <p class="img-discr-item-text">${s}</p>
                </li>
                <li class="img-discr-item">
                    <h2 class="img-discr-item-header">Comments</h2>
                    <p class="img-discr-item-text">${d}</p>
                </li><li class="img-discr-item">
                    <h2 class="img-discr-item-header">Downloads</h2>
                    <p class="img-discr-item-text">${x}</p>
                </li>
            </ul>
        </div>
    </li>`).join("")}class S{constructor(e,a){this.buttonEL=e,this.hiddenClass=a}hide(){this.buttonEL.classList.add(this.hiddenClass)}show(){this.buttonEL.classList.remove(this.hiddenClass)}disable(){this.buttonEL.disabled=!0}enable(){this.buttonEL.disabled=!1}}class A{constructor(e){this.spinerEl=e}hide(){this.spinerEl.style.display="none"}show(){this.spinerEl.style.display="block"}}const m=document.querySelector(".search-img-form"),C=document.querySelector(".loader"),g=document.querySelector(".img-container-list"),h=document.querySelector(".load-more"),o=new S(h,"is-hidden"),n=new A(C),r={page:1,per_page:15,q:"",maxPage:0};m.addEventListener("submit",E);o.hide();n.hide();async function E(t){if(t.preventDefault(),n.show(),g.innerHTML="",r.q=t.currentTarget.elements.name.value.trim().toLowerCase(),!r.q){c.show({title:"Caution",titleColor:"#FAFAFB",titleSize:"16px",titleLineHeight:"24px",position:"topRight",maxWidth:"432px",message:"Ops.. You forgot to write the keyword!",messageColor:"#FAFAFB",messageSize:"16px",messageLineHeight:" 24px",backgroundColor:"#FFA000"}),n.hide(),m.reset();return}o.show(),o.disable(),r.page=1;try{const{hits:e,totalHits:a}=await u(r);r.maxPage=Math.ceil(a/r.per_page),f(e),r.maxPage>1?(o.enable(),h.addEventListener("click",y)):o.hide()}catch(e){g.innerHTML="",n.hide(),o.hide(),e.name==="TypeError"&&e.message.includes("Failed to fetch")?c.show({title:"Error",titleColor:"#FAFAFB",titleSize:"16px",titleLineHeight:"24px",position:"topRight",maxWidth:"432px",message:"No internet connection",messageColor:"#FAFAFB",messageSize:"16px",messageLineHeight:" 24px",backgroundColor:"#EF4040"}):(n.hide(),o.hide(),c.show({title:"Error",titleColor:"#FAFAFB",titleSize:"16px",titleLineHeight:"24px",position:"topRight",maxWidth:"432px",message:`An error occurred: ${e.message}`,messageColor:"#FAFAFB",messageSize:"16px",messageLineHeight:" 24px",backgroundColor:"#EF4040"}))}finally{m.reset()}}async function y(){o.hide(),n.show(),r.page+=1;try{const{hits:t}=await u(r);f(t),v(),o.show()}catch(t){n.hide(),c.show({title:"Error",titleColor:"#FAFAFB",titleSize:"16px",titleLineHeight:"24px",position:"topRight",maxWidth:"432px",message:`An error occurred: ${t.message}`,messageColor:"#FAFAFB",messageSize:"16px",messageLineHeight:" 24px",backgroundColor:"#EF4040"})}finally{r.page===r.maxPage?(o.hide(),h.removeEventListener("click",y),c.show({position:"topRight",maxWidth:"432px",message:"We're sorry, but you've reached the end of search results.",messageColor:"#FAFAFB",messageSize:"16px",messageLineHeight:" 24px",backgroundColor:"#09F"})):o.enable()}}function v(){const e=document.querySelector(".img-container-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
